version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: extraspace_db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      TZ: Asia/Almaty
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d
    ports:
      - "${DB_PORT:-5432}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-extraspace} -d ${DB_NAME:-extraspace}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - extraspace_network

volumes:
  postgres_data:

networks:
  extraspace_network:
    driver: bridge